# Generated by Django 3.1 on 2020-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivedcompass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='bruh', max_length=256),
            preserve_default=False,
        ),
    ]
